export function getBankList() {
    const list = {
        "001": { word: "BAM", name: "Bank Al-maghrib" },
        "002": { word: "AB", name: "Arab Bank" },
        "005": { word: "UMB", name: "Union Marocaine de Banques" },
        "007": { word: "AWB", name: "Attijariwafa bank" },
        "009": { word: "SBC", name: "Societe de Banque & de Crédit" },
        "011": { word: "BMCE", name: "" },
        "013": { word: "BMCI", name: "" },
        "019": { word: "WB", name: "World Bank - WB" },
        "021": { word: "CDM", name: "Crédit du Maroc" },
        "022": { word: "SGMB", name: "Société Générale Maroc" },
        "023": { word: "ABN", name: "" },
        "025": { word: "BMAO", name: "Bank of Africa" },
        "026": { word: "UNIB", name: "Union Bancaria Hispano Marroqui Uniban - UNIB" },
        "028": { word: "CITI", name: "CITIBANK" },
        "031": { word: "SMDC", name: "Societe Marocaine de Depôt et de Crédit" },
        "032": { word: "BEX", name: "" },
        "054": { word: "CDG", name: "" },
        "101": { word: "BPA", name: "Banque Populaire - BPA" },
        "105": { word: "BPH", name: "Banque Populaire - BPH" },
        "109": { word: "BPBM", name: "Banque Populaire - BPBM" },
        "117": { word: "BPE", name: "Banque Populaire - BPE" },
        "127": { word: "BPF", name: "Banque Populaire - BPF" },
        "133": { word: "BPG", name: "Banque Populaire - BPG" },
        "140": { word: "BPKH", name: "Banque Populaire - BPKH" },
        "143": { word: "BPL", name: "Banque Populaire - BPL" },
        "145": { word: "BPM", name: "Banque Populaire - BPM" },
        "148": { word: "BPMK", name: "Banque Populaire - BPMK" },
        "149": { word: "BPRI", name: "Banque Populaire - BPRI" },
        "150": { word: "BPN", name: "Banque Populaire - BPN" },
        "155": { word: "BPOU", name: "Banque Populaire - BPOU" },
        "157": { word: "BPO", name: "Banque Populaire - BPO" },
        "159": { word: "BPS", name: "Banque Populaire - BPS" },
        "164": { word: "BPTA", name: "Banque Populaire - BPTA" },
        "169": { word: "BPTZ", name: "Banque Populaire - BPTZ" },
        "172": { word: "BPTE", name: "Banque Populaire - BPTE" },
        "175": { word: "BPTI", name: "Banque Populaire - BPTI" },
        "178": { word: "BPCA", name: "Banque Populaire - BPCA" },
        "181": { word: "BPR", name: "Banque Populaire - BPR" },
        "190": { word: "BCP", name: "Banque Centrale Populaire" },
        "195": { word: "BPCE", name: "Banque Populaire - BPCE" },
        "197": { word: "BPCS", name: "Banque Populaire - BPCS" },
        "205": { word: "BNDE", name: "Banque Nationale pour le Développement Économique" },
        "210": { word: "CDG", name: "" },
        "225": { word: "CNCA", name: "Crédit Agricole" },
        "230": { word: "CIH", name: "CIH Bank" },
        "310": { word: "TGR", name: "Trésorerie Générale du Royaume" },
        "350": { word: "CCP", name: "Banque Centrale Populaire" },
    };
    return list;
}